OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhoneShop.Web.Models
{
    public class Brand
    {
        [Display(Name = "Brand id")]
        [Required]
        public int Id { get; set; }
        [Display(Name = "Brand name")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Yearly income (usd)")]
        [Required]
        public int Forgalom { get; set; }
        [Display(Name = "Producing only smart devices")]
        [Required]
        public string Csakinf { get; set; }
        [Display(Name = "Software used by the brand")]
        [Required]
        public string Szoftver { get; set; }
        [Display(Name = "Web url")]
        [Required]
        public string Weblap { get; set; }
    }
}

OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Models/BrandsViewModel.cs
using PhoneShop.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhoneShop.Web.Models
{
    public class BrandsViewModel
    {
        public Brand EditedBrand { get; set; }
        public List<Brand> ListOfBrands { get; set; }
    }
}

OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Controllers/BrandsController.cs
using AutoMapper;
using PhoneShop.Data;
using PhoneShop.Repository;
using PhoneShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhoneShop.Web.Controllers
{
    public class BrandsController : Controller
    {
        PhoneShop.Logic.BusinessLogic logic;
        IMapper mapper;
        BrandsViewModel model;
        

        public BrandsController()
        {
            Database1Entities db = new Database1Entities();
            GyártóRepository brandRepo = new GyártóRepository(db);
            logic = new Logic.BusinessLogic(brandRepo);
            mapper = MapperFactory.CreateMapper();
            model = new BrandsViewModel();
            model.EditedBrand = new Brand();

            var brands = logic.ReadGyartokforprog4();
            model.ListOfBrands = mapper.Map<IList<Data.Gyártó>, List<Models.Brand>>(brands);
        }

        private Brand GetOneBrand(int id)
        {
            Gyártó oneBrand = logic.GetGyartoforprog4(id);
            return mapper.Map<Gyártó, Brand>(oneBrand);
        }

        // GET: Brands
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("BrandIndex", model);
        }

        // GET: Brands/Details/5
        public ActionResult Details(int id)
        {
            return View("BrandDetails", GetOneBrand(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Fail";
            if (logic.DeleteGyarto(id))
            {
                TempData["editResult"] = "Delete OK";
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            model.EditedBrand = GetOneBrand(id);
            return View("BrandIndex", model);
        }

        [HttpPost]
        public ActionResult Edit(Brand brand, string editAction)
        {
            if (ModelState.IsValid && brand != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction=="AddNew")
                {
                    logic.AddGyartoForProg4(brand.Name, brand.Forgalom, brand.Csakinf, brand.Szoftver, brand.Weblap);
                }
                else
                {
                    if (!logic.UpdateGyartokforprog4(brand.Id, brand.Name, brand.Forgalom, brand.Csakinf, brand.Szoftver, brand.Weblap))
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                model.EditedBrand = brand;
                return View("BrandIndex", model);
            }

        }

    }
}

OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Views/Brands/BrandDetails.cshtml
@model PhoneShop.Web.Models.Brand
@{
	ViewBag.Title = "BrandDetails";
}

<h2>Datasheet of one brand</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
	<tr>
		<td>@Html.DisplayNameFor(m => m.Id)</td>
		<td>@Html.DisplayFor(m => m.Id)</td>
	</tr>
	<tr>
		<td>@Html.DisplayNameFor(m => m.Name)</td>
		<td>@Html.DisplayFor(m => m.Name)</td>
	</tr>
	<tr>
		<td>@Html.DisplayNameFor(m => m.Forgalom)</td>
		<td>@Html.DisplayFor(m => m.Forgalom)</td>
	</tr>
	<tr>
		<td>@Html.DisplayNameFor(m => m.Csakinf)</td>
		<td>@Html.DisplayFor(m => m.Csakinf)</td>
	</tr>
	<tr>
		<td>@Html.DisplayNameFor(m => m.Szoftver)</td>
		<td>@Html.DisplayFor(m => m.Szoftver)</td>
	</tr>
	<tr>
		<td>@Html.DisplayNameFor(m => m.Weblap)</td>
		<td>@Html.DisplayFor(m => m.Weblap)</td>
	</tr>
</table>

OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Views/Brands/BrandEdit.cshtml
@model PhoneShop.Web.Models.Brand

<h2>Edit one brand</h2>

@using (Html.BeginForm("Edit", "Brands"))
{
	@Html.ValidationSummary()

	@Html.AntiForgeryToken()

	@Html.HiddenFor(m => m.Id)
	@Html.Hidden("editAction", ViewData["editAction"].ToString());

	<div class="editor-label">@Html.LabelFor(m => m.Name)</div>
	<div class="editor-field">@Html.EditorFor(m => m.Name)</div>

	<div class="editor-label">@Html.LabelFor(m => m.Forgalom)</div>
	<div class="editor-field">@Html.EditorFor(m => m.Forgalom)</div>

	<div class="editor-label">@Html.LabelFor(m => m.Csakinf)</div>
	<div class="editor-field">@Html.EditorFor(m => m.Csakinf)</div>

	<div class="editor-label">@Html.LabelFor(m => m.Szoftver)</div>
	<div class="editor-field">@Html.EditorFor(m => m.Szoftver)</div>

	<div class="editor-label">@Html.LabelFor(m => m.Weblap)</div>
	<div class="editor-field">@Html.EditorFor(m => m.Weblap)</div>

	<input type="submit" value="SEND">

}

OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Views/Brands/BrandIndex.cshtml
@model PhoneShop.Web.Models.BrandsViewModel
@{
    ViewBag.Title = "Brands Index";
}

<h2>Brands Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

	@Html.Partial("BrandEdit",Model.EditedBrand)

	@Html.Partial("BrandList",Model.ListOfBrands)

OENIK_PROG3_2019_1_VVEYPS/PhoneShop.Web/Views/Brands/BrandList.cshtml
@model IEnumerable<PhoneShop.Web.Models.Brand>


<h2>List of brands</h2>
@if (Model.Count() == 0)
{
	<p>No data in the database</p>
}
else
{
	<table border="1">
		<tr>
			<th>@Html.DisplayNameFor(m => m.First().Name)</th>
			<th>Datasheet</th>
			<th>Delete</th>
			<th>Edit</th>
		</tr>
		@foreach (var item in Model)
		{
			<tr>
				<td>@Html.DisplayFor(m => item.Name)</td>
				<td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
				<td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
				<td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
			</tr>
		}
	</table>
}